/**
 * Compile contracts/RitualArena.sol with solc and emit lib/arena.ts
 * (the ABI + bytecode the frontend and the deploy script consume).
 *
 *   bun run build:contract
 *
 * No private key or network needed — this is a pure local compile.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import solc from "solc";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(root, "contracts", "RitualArena.sol");
const OUT = join(root, "lib", "arena.ts");
const NAME = "RitualArena";

const source = readFileSync(SRC, "utf8");

const input = {
  language: "Solidity",
  sources: { "RitualArena.sol": { content: source } },
  settings: {
    optimizer: { enabled: true, runs: 200 },
    outputSelection: { "*": { "*": ["abi", "evm.bytecode.object"] } },
  },
};

const output = JSON.parse(solc.compile(JSON.stringify(input)));

const errors = (output.errors ?? []).filter((e: { severity: string }) => e.severity === "error");
if (errors.length) {
  for (const e of errors) console.error(e.formattedMessage ?? e.message);
  throw new Error("Solidity compilation failed");
}
for (const w of output.errors ?? []) console.warn(w.formattedMessage ?? w.message);

const artifact = output.contracts["RitualArena.sol"][NAME];
const abi = artifact.abi;
const bytecode = "0x" + artifact.evm.bytecode.object;

const file = `// ⚠️ Generated by scripts/build-contract.ts — do not edit by hand.
// Source: contracts/RitualArena.sol  ·  run \`bun run build:contract\` to refresh.

export const ARENA_ABI = ${JSON.stringify(abi, null, 2)} as const;

export const ARENA_BYTECODE = ${JSON.stringify(bytecode)} as const;

/** Deployed address (set NEXT_PUBLIC_ARENA_ADDRESS after deploying). */
export const ARENA_ADDRESS = (process.env.NEXT_PUBLIC_ARENA_ADDRESS ?? "") as \`0x\${string}\` | "";

/** Fixed fee to record a win — keep in sync with SUBMIT_FEE in the contract. */
export const SUBMIT_FEE_ETHER = "0.001";
`;

writeFileSync(OUT, file);
console.log(`✓ compiled ${NAME} → ${OUT}`);
console.log(`  abi entries: ${abi.length}  ·  bytecode: ${(bytecode.length - 2) / 2} bytes`);
